services:
  server:
    image: shahadathhs/peoplesync-server:latest
    platform: linux/amd64
    container_name: peoplesync_api
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 5010:5010
    depends_on:
      - db
      - redis
    command: >
      sh -c "
        npx prisma migrate deploy &&
        npm run start
      "

  db:
    image: postgres
    container_name: peoplesync_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: peoplesync_db
    volumes:
      - peoplesync_db:/var/lib/postgresql/data
    ports:
      - '5404:5432'

  redis:
    image: redis
    container_name: peoplesync_redis
    restart: always
    ports:
      - '6384:6379'

volumes:
  peoplesync_db:
