name: Lint, Format, Build, Push & Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches:
      - '**'

jobs:
  ci-check:
    name: Lint, Format, Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 24

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run Lint
        run: pnpm lint

      - name: Format Check
        run: pnpm format

      - name: Build Project
        run: pnpm build

  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: ci-check
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/peoplesync-server:latest

  deploy:
    name: Trigger Render Deployment
    runs-on: ubuntu-latest
    needs: build-and-push
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Call Render Deploy Hook for Docker Deployment
        run: |
          curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}
      - name: Confirm Deployment Triggered
        run: echo "Render deployment triggered successfully."
