name: CI Check Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci-check:
    name: CI - Lint, Format, Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 24

      - name: Enable pnpm
        run: corepack enable && corepack prepare pnpm@latest --activate

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Run Lint
        run: pnpm lint

      - name: Format Check
        run: pnpm format

      - name: Build Project
        run: pnpm build
